import { motion } from 'framer-motion';
import { ArrowLeft, Smartphone } from 'lucide-react';
import { Link, useSearchParams } from 'react-router-dom';
import { Button } from '../../components/Button';
import { Input } from '../../components/Input';

const Setup2FAPage = () => {
    const [searchParams] = useSearchParams();
    const method = searchParams.get('method') || 'authenticator';

    return (
        <div className="max-w-2xl mx-auto py-10 px-4">
            <Link to="/settings/security" className="inline-flex items-center text-sm text-gray-500 hover:text-primary mb-8">
                <ArrowLeft className="h-4 w-4 mr-2" /> Back to Security
            </Link>

            <motion.div
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                className="bg-white shadow-sm ring-1 ring-gray-900/5 rounded-2xl p-8"
            >
                <div className="text-center mb-8">
                    <div className="bg-primary/10 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4">
                        <Smartphone className="h-8 w-8 text-primary" />
                    </div>
                    <h1 className="text-2xl font-bold text-gray-900">Setup 2FA via {method}</h1>
                    <p className="text-gray-600 mt-2">Follow the steps below to secure your account.</p>
                </div>

                <div className="space-y-8">
                    <div className="flex items-start space-x-4">
                        <div className="bg-gray-100 w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 font-bold text-gray-600">1</div>
                        <div>
                            <p className="font-medium text-gray-900">Scan the QR Code</p>
                            <p className="text-sm text-gray-500 mt-1">Open your authenticator app and scan the code below.</p>
                            <div className="mt-4 w-48 h-48 bg-gray-100 rounded-xl flex items-center justify-center border-2 border-dashed border-gray-200">
                                <span className="text-xs text-gray-400 font-mono">[QR CODE PLACEHOLDER]</span>
                            </div>
                        </div>
                    </div>

                    <div className="flex items-start space-x-4">
                        <div className="bg-gray-100 w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 font-bold text-gray-600">2</div>
                        <div className="flex-grow">
                            <p className="font-medium text-gray-900">Enter Verification Code</p>
                            <p className="text-sm text-gray-500 mt-1">Enter the 6-digit code generated by your app.</p>
                            <div className="mt-4">
                                <Input
                                    label="6-digit Code"
                                    placeholder="000 000"
                                    className="text-center text-2xl tracking-widest font-bold"
                                    maxLength={6}
                                />
                            </div>
                        </div>
                    </div>

                    <Button className="w-full py-6 text-lg">
                        Complete Setup
                    </Button>
                </div>
            </motion.div>
        </div>
    );
};

export default Setup2FAPage;
